// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv0lXwJv6BsFZFIQsUzc0yECe5CkDDLug',
    appId: '1:465495513947:web:fee1f875c57118b7b1d87e',
    messagingSenderId: '465495513947',
    projectId: 'sarathigrocery',
    authDomain: 'sarathigrocery.firebaseapp.com',
    storageBucket: 'sarathigrocery.firebasestorage.app',
    measurementId: 'G-YRNQXK0F03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF-1hwEntrCAeY2iqoTQSpYFf67trwBhQ',
    appId: '1:465495513947:android:3070a2739582327fb1d87e',
    messagingSenderId: '465495513947',
    projectId: 'sarathigrocery',
    storageBucket: 'sarathigrocery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCLoMorh7IKPIko0zWL9KwghFGFutx01M',
    appId: '1:465495513947:ios:a6fc38992cf6c17cb1d87e',
    messagingSenderId: '465495513947',
    projectId: 'sarathigrocery',
    storageBucket: 'sarathigrocery.firebasestorage.app',
    iosBundleId: 'com.manandharsudhir.sarathigrocery',
  );
}
